-- core/skill.lua
-- 技能系统模块：reg/RegisterExtSkill/ReRegisterExtSkill/ReloadAllSkills/load_sys_enabled/save_sys_enabled/SkillManager/OpenSysSkillManager/OpenExtSkillManager/sendget/postmsg/buildParameters/getAllTools/checkSkillPermission/showSkillPermissionDialog/readSkillFile/loadSkill/writeFile/readFile/ensureDir/skillBasePath/skillFilePath/pm_perm.*mem_compressor.*setAIPermission/getAIPermission/RegisterProjectSkill/UnregisterProjectSkill/CallProjectSkill/ProjectSkillManager/deleteSkill

